// ===================================
// DATOS COMPLETOS DEL CATÁLOGO
// Imperial Love - Medellín
// ===================================

const products = [
    // Arreglos pequeños en rosas (1-6)
    { id: 1, code: "001", category: "Arreglos pequeños en rosas", name: "Primer Latido", description: "Delicado detalle con 3 rosas frescas que expresan cariño sincero. Perfecto para gestos espontáneos que tocan el corazón.", price: 50000, image: "assets/catalog/cod_001.webp" },
    { id: 2, code: "002", category: "Arreglos pequeños en rosas", name: "Gesto Espontáneo", description: "Ramo encantador con 8 rosas envueltas con elegancia. Ideal para sorpresas inesperadas llenas de significado.", price: 75000, image: "assets/catalog/cod_002.webp" },
    { id: 3, code: "003", category: "Arreglos pequeños en rosas", name: "Dulce Inicio", description: "Bouquet tierno de 8 rosas cuidadosamente seleccionadas. Transmite amor en su forma más pura y natural.", price: 75000, image: "assets/catalog/cod_003.webp" },
    { id: 4, code: "004", category: "Arreglos pequeños en rosas", name: "Ternura Sincera", description: "Arreglo armonioso con 10 rosas que hablan sin palabras. Perfecto para momentos especiales del corazón.", price: 100000, image: "assets/catalog/cod_004.webp" },
    { id: 5, code: "005", category: "Arreglos pequeños en rosas", name: "Conexión Natural", description: "Hermoso ramo de 10 rosas con presentación sofisticada. Expresa sentimientos profundos con elegancia atemporal.", price: 118750, image: "assets/catalog/cod_005.webp" },
    { id: 6, code: "006", category: "Arreglos pequeños en rosas", name: "Encanto Clásico", description: "Bouquet tradicional con 12 rosas que nunca pasan de moda. Símbolo eterno de amor y admiración verdadera.", price: 137500, image: "assets/catalog/cod_006.webp" },
    
    // Combinación de Rosas (7-15)
    { id: 7, code: "007", category: "Combinación de Rosas", name: "Fusión Armoniosa", description: "Ramo vibrante de 20 rosas en combinación perfecta de colores. Transmite alegría, amor y buenos deseos en cada tono.", price: 162500, image: "assets/catalog/cod_007.webp" },
    { id: 8, code: "008", category: "Combinación de Rosas", name: "Elegancia Mixta", description: "Arreglo sofisticado con 24 rosas en tonos complementarios. Diseñado para conquistar con estilo y distinción única.", price: 181250, image: "assets/catalog/cod_008.webp" },
    { id: 9, code: "009", category: "Combinación de Rosas", name: "Contraste Perfecto", description: "Bouquet equilibrado de 24 rosas que juegan con colores contrastantes. Ideal para personalidades únicas y especiales.", price: 181250, image: "assets/catalog/cod_009.webp" },
    { id: 10, code: "010", category: "Combinación de Rosas", name: "Dualidad Romántica", description: "Hermoso conjunto de 24 rosas que combina pasión y delicadeza. Perfecto para expresar sentimientos complejos y profundos.", price: 187500, image: "assets/catalog/cod_010.webp" },
    { id: 11, code: "011", category: "Combinación de Rosas", name: "Sinfonía de Colores", description: "Arreglo premium con 24 rosas en mezcla cuidadosamente seleccionada. Cada color cuenta una historia de amor diferente.", price: 187500, image: "assets/catalog/cod_011.webp" },
    { id: 12, code: "012", category: "Combinación de Rosas", name: "Impacto Dual", description: "Ramo imponente de 48 rosas en combinación espectacular. Diseñado para dejar huella imborrable en el corazón.", price: 262500, image: "assets/catalog/cod_012.webp" },
    { id: 13, code: "013", category: "Combinación de Rosas", name: "Abundancia Mixta", description: "Bouquet abundante con 48 rosas en fusión armoniosa de tonos. Para quienes quieren sorprender en grande con estilo.", price: 262500, image: "assets/catalog/cod_013.webp" },
    { id: 14, code: "014", category: "Combinación de Rosas", name: "Explosión de Amor", description: "Arreglo espectacular de 48 rosas que desbordan emoción. Perfecto para declaraciones importantes y momentos únicos.", price: 262500, image: "assets/catalog/cod_014.webp" },
    { id: 15, code: "015", category: "Combinación de Rosas", name: "Grandeza Combinada", description: "Ramo majestuoso con 48 rosas en presentación premium. Transmite amor sin límites ni fronteras emocionales.", price: 262500, image: "assets/catalog/cod_015.webp" },
    
    // Unicolor Rosas (17-19)
    { id: 17, code: "017", category: "Unicolor Rosas", name: "Pureza Monocromática", description: "Elegante bouquet de 24 rosas en un solo tono. La simplicidad que habla más fuerte que mil palabras.", price: 156250, image: "assets/catalog/cod_017.webp" },
    { id: 18, code: "018_a", category: "Unicolor Rosas", name: "Esencia Única", description: "Arreglo sofisticado con 24 rosas del mismo color. Transmite mensaje claro, directo y lleno de significado profundo.", price: 175000, image: "assets/catalog/cod_018_a.webp" },
    { id: 18.1, code: "018_b", category: "Unicolor Rosas", name: "Monocromo Elegante", description: "Ramo armonioso de 24 rosas unicolor con presentación impecable. Elegancia pura que conquista desde la primera mirada.", price: 175000, image: "assets/catalog/cod_018_b.webp" },
    { id: 19, code: "019", category: "Unicolor Rosas", name: "Intensidad Unicolor", description: "Bouquet imponente con 48 rosas en tono único. Diseñado para causar impacto visual y emocional inolvidable.", price: 262500, image: "assets/catalog/cod_019.webp" },
    
    // Rosas Rojas (20-26)
    { id: 20, code: "020", category: "Rosas Rojas", name: "Pasión Clásica", description: "Ramo tradicional de 24 rosas rojas que simbolizan amor verdadero. El regalo que nunca falla para expresar sentimientos profundos.", price: 150000, image: "assets/catalog/cod_020.webp" },
    { id: 21, code: "021", category: "Rosas Rojas", name: "Fuego del Alma", description: "Arreglo intenso con 48 rosas rojas que arden de pasión. Perfecto para declaraciones importantes y aniversarios memorables.", price: 250000, image: "assets/catalog/cod_021.webp" },
    { id: 22, code: "022", category: "Rosas Rojas", name: "Declaración Intensa", description: "Bouquet poderoso de 60 rosas rojas que no necesitan palabras. Transmite amor fuerte, seguro y sin límites.", price: 312500, image: "assets/catalog/cod_022.webp" },
    { id: 23, code: "023", category: "Rosas Rojas", name: "Amor Desbordante", description: "Ramo espectacular con 72 rosas rojas en presentación premium. Para quienes aman en grande y sin restricciones emocionales.", price: 350000, image: "assets/catalog/cod_023.webp" },
    { id: 24, code: "024", category: "Rosas Rojas", name: "Centenario de Pasión", description: "Arreglo majestuoso de 100 rosas rojas que roban el aliento. Diseñado para momentos que merecen ser eternos.", price: 481250, image: "assets/catalog/cod_024.webp" },
    { id: 25, code: "025", category: "Rosas Rojas", name: "Océano Rojo", description: "Bouquet monumental con 200 rosas rojas que inundan de amor. Perfecto para celebraciones extraordinarias y declaraciones únicas.", price: 875000, image: "assets/catalog/cod_025.webp" },
    { id: 26, code: "026", category: "Rosas Rojas", name: "Universo Carmesí", description: "Ramo colosal de 400 rosas rojas que trascienden lo imaginable. Para quienes buscan impactar como nunca antes en la vida.", price: 1575000, image: "assets/catalog/cod_026.webp" },
    
    // ROSAS Y ACCESORIOS (27-38)
    { id: 27, code: "027", category: "ROSAS Y ACCESORIOS", name: "Corona de Ternura", description: "Ramo elegante con 24 rosas y corona pequeña decorativa. Detalle perfecto para hacer sentir especial a quien lo recibe.", price: 187500, image: "assets/catalog/cod_027.webp" },
    { id: 28, code: "028", category: "ROSAS Y ACCESORIOS", name: "Mensaje Personalizado", description: "Arreglo romántico de 24 rosas con listón que lleva tu mensaje único. Las flores hablan, pero tus palabras las complementan.", price: 225000, image: "assets/catalog/cod_028.webp" },
    { id: 29, code: "029", category: "ROSAS Y ACCESORIOS", name: "Declaración Grande", description: "Bouquet imponente de 48 rosas con listón personalizado premium. Diseñado para expresar lo que el corazón siente intensamente.", price: 287500, image: "assets/catalog/cod_029.webp" },
    { id: 30, code: "030", category: "ROSAS Y ACCESORIOS", name: "Vuelo de Amor", description: "Ramo encantador con 24 rosas, corona pequeña y mariposa decorativa. Simboliza la transformación que el amor verdadero genera.", price: 200000, image: "assets/catalog/cod_030.webp" },
    { id: 31, code: "031", category: "ROSAS Y ACCESORIOS", name: "Guardián Tierno", description: "Arreglo dulce de 24 rosas con vela decorativa en forma de oso. Combina romance con ternura en un solo detalle memorable.", price: 212500, image: "assets/catalog/cod_031.webp" },
    { id: 32, code: "032", category: "ROSAS Y ACCESORIOS", name: "Transformación Doble", description: "Bouquet sofisticado con 24 rosas, corona grande y mariposas delicadas. Representa evolución del amor en cada pétalo.", price: 200000, image: "assets/catalog/cod_032.webp" },
    { id: 32.1, code: "032_a", category: "ROSAS Y ACCESORIOS", name: "Logro Coronado", description: "Ramo especial de 24 rosas con corona pequeña y birrete decorativo. Perfecto para celebrar éxitos académicos y profesionales importantes.", price: 150000, image: "assets/catalog/cod_032_a.webp" },
    { id: 33, code: "033", category: "ROSAS Y ACCESORIOS", name: "Lazo del Corazón", description: "Arreglo romántico con 24 rosas, corona y listón pequeño elegante. Cada detalle habla de amor cuidadosamente expresado.", price: 206250, image: "assets/catalog/cod_033.webp" },
    { id: 34, code: "034", category: "ROSAS Y ACCESORIOS", name: "Guardián del Amor", description: "Bouquet completo de 24 rosas con corona, vela de oso y listón personalizado. La combinación perfecta entre romance y ternura.", price: 262500, image: "assets/catalog/cod_034.webp" },
    { id: 35, code: "035", category: "ROSAS Y ACCESORIOS", name: "Abrazo Gigante", description: "Ramo abundante de 48 rosas con vela decorativa grande de oso. Transmite amor protector, cálido y sin condiciones.", price: 280600, image: "assets/catalog/cod_035.webp" },
    { id: 36, code: "036", category: "ROSAS Y ACCESORIOS", name: "Vuelo Personalizado", description: "Arreglo premium con 48 rosas, corona, mariposas y listón con tu mensaje. Diseñado para impactar emocionalmente desde el primer vistazo.", price: 325000, image: "assets/catalog/cod_036.webp" },
    { id: 37, code: "037", category: "ROSAS Y ACCESORIOS", name: "Dulzura Completa", description: "Bouquet espectacular de 48 rosas acompañadas de deliciosos dulces selectos. Romance que conquista corazón y paladar simultáneamente.", price: 337500, image: "assets/catalog/cod_037.webp" },
    { id: 38, code: "038", category: "ROSAS Y ACCESORIOS", name: "Dulce Transformación", description: "Ramo majestuoso con 48 rosas, mariposas decorativas y dulces gourmet. La fusión perfecta entre amor, belleza y sabor.", price: 362500, image: "assets/catalog/cod_038.webp" },
    
    // Lirios y Rosas (39-46)
    { id: 39, code: "039", category: "Lirios y Rosas", name: "Dúo Delicado", description: "Arreglo armonioso con 10 rosas y 3 lirios elegantes. Combina romance con pureza en presentación sofisticada y natural.", price: 156250, image: "assets/catalog/cod_039.webp" },
    { id: 40, code: "040", category: "Lirios y Rosas", name: "Armonía Dual", description: "Bouquet equilibrado de 18 rosas y 2 lirios frescos. Transmite amor sereno, profundo y lleno de significado verdadero.", price: 187500, image: "assets/catalog/cod_040.webp" },
    { id: 41, code: "041", category: "Lirios y Rosas", name: "Equilibrio Natural", description: "Ramo perfecto con 20 rosas y 4 lirios majestuosos. Ideal para quienes buscan belleza y elegancia en perfecta proporción.", price: 187500, image: "assets/catalog/cod_041.webp" },
    { id: 42, code: "042", category: "Lirios y Rosas", name: "Fusión Elegante", description: "Arreglo sofisticado de 24 rosas y 5 lirios aromáticos. Diseñado para conquistar con estilo, clase y distinción absoluta.", price: 237500, image: "assets/catalog/cod_042.webp" },
    { id: 43, code: "043", category: "Lirios y Rosas", name: "Serenidad Abundante", description: "Bouquet abundante con 30 rosas y 3 lirios que transmiten paz. Perfecto para momentos especiales que merecen ser recordados.", price: 262500, image: "assets/catalog/cod_043.webp" },
    { id: 44, code: "044", category: "Lirios y Rosas", name: "Explosión Floral", description: "Ramo espectacular de 24 rosas y 10 lirios en presentación premium. Combina abundancia con elegancia en cada detalle cuidado.", price: 275000, image: "assets/catalog/cod_044.webp" },
    { id: 45, code: "045", category: "Lirios y Rosas", name: "Jardín Romántico", description: "Arreglo encantador con 30 rosas y 5 lirios frescos seleccionados. Transmite amor natural, puro y sin artificios innecesarios.", price: 287500, image: "assets/catalog/cod_045.webp" },
    { id: 46, code: "046", category: "Lirios y Rosas", name: "Jardín Encantado", description: "Bouquet mágico de 30 rosas, 5 lirios y mariposa decorativa. Representa la belleza que el amor verdadero crea naturalmente.", price: 293750, image: "assets/catalog/cod_046.webp" },
    
// Rosas y girasoles (48-53)
    { id: 48, code: "048", category: "Rosas y girasoles", name: "Sol y Pasión", description: "Ramo vibrante con 24 rosas y 2 girasoles radiantes. Combina intensidad emocional con alegría luminosa en perfecta armonía.", price: 218750, image: "assets/catalog/cod_048.webp" },
    { id: 49, code: "049", category: "Rosas y girasoles", name: "Brillo Múltiple", description: "Arreglo alegre de 24 rosas y 5 girasoles pequeños. Transmite amor iluminado por la felicidad y buenos deseos sinceros.", price: 237500, image: "assets/catalog/cod_049.webp" },
    { id: 50, code: "050", category: "Rosas y girasoles", name: "Estrella Central", description: "Bouquet imponente con 48 rosas y 1 girasol protagonista. El sol que brilla entre pasiones, perfecto para personalidades únicas.", price: 268750, image: "assets/catalog/cod_050.webp" },
    { id: 51, code: "051", category: "Rosas y girasoles", name: "Sol Imperial", description: "Ramo majestuoso de 72 rosas y 1 girasol central. Diseñado para quienes aman con intensidad pero celebran la luz interior.", price: 375000, image: "assets/catalog/cod_051.webp" },
    { id: 52, code: "052", category: "Rosas y girasoles", name: "Centenario Solar", description: "Arreglo espectacular con 100 rosas y 1 girasol radiante. Representa amor grande iluminado por alegría y esperanza eterna.", price: 487500, image: "assets/catalog/cod_052.webp" },
    { id: 53, code: "053", category: "Rosas y girasoles", name: "Constelación Dorada", description: "Bouquet monumental de 100 rosas y 4 girasoles brillantes. Para quienes quieren expresar amor sin límites lleno de luz.", price: 500000, image: "assets/catalog/cod_053.webp" },
    
    // Girasoles (54-62)
    { id: 54, code: "054", category: "Girasoles", name: "Trío de Luz", description: "Arreglo sencillo con 3 girasoles frescos y radiantes. Perfecto para detalles espontáneos que alegran el día con naturalidad pura.", price: 75000, image: "assets/catalog/cod_054.webp" },
    { id: 55, code: "055", category: "Girasoles", name: "Cuarteto Solar", description: "Bouquet alegre de 4 girasoles que transmiten energía positiva. Ideal para sorpresas llenas de luz y buenos deseos sinceros.", price: 93750, image: "assets/catalog/cod_055.webp" },
    { id: 56, code: "056", category: "Girasoles", name: "Siete Soles", description: "Ramo vibrante con 7 girasoles en presentación elegante. Transmite felicidad, esperanza y amor luminoso en cada pétalo dorado.", price: 137500, image: "assets/catalog/cod_056.webp" },
    { id: 57, code: "057", category: "Girasoles", name: "Círculo Luminoso", description: "Arreglo abundante de 10 girasoles que irradian alegría. Diseñado para celebrar momentos especiales con energía positiva desbordante.", price: 162500, image: "assets/catalog/cod_057.webp" },
    { id: 58, code: "058", category: "Girasoles", name: "Docena Radiante", description: "Bouquet completo con 12 girasoles en presentación premium. Perfecto para quienes aman la luz, la vida y la felicidad sincera.", price: 181250, image: "assets/catalog/cod_058.webp" },
    { id: 59, code: "059", category: "Girasoles", name: "Veinte Rayos", description: "Ramo espectacular de 20 girasoles que roban miradas. Para sorpresas grandes que necesitan toda la luz del sol reunida.", price: 287500, image: "assets/catalog/cod_059.webp" },
    { id: 60, code: "060", category: "Girasoles", name: "Fusión Solar", description: "Arreglo equilibrado con 5 girasoles y 15 rosas frescas. Combina alegría radiante con romance en perfecta armonía emocional.", price: 212500, image: "assets/catalog/cod_060.webp" },
    { id: 61, code: "061", category: "Girasoles", name: "Mini Explosión", description: "Bouquet especial de 15 girasoles mini y 5 rosas (solo disponible por temporadas). Detalle único que transmite ternura luminosa.", price: 250000, image: "assets/catalog/cod_061.webp" },
    { id: 62, code: "062", category: "Girasoles", name: "Mensaje Solar", description: "Ramo personalizado con 12 girasoles, 8 rosas y listón con tu mensaje. Las flores hablan, pero tus palabras las hacen eternas.", price: 262500, image: "assets/catalog/cod_062.webp" },
    
    // Solitarios (63-68)
    { id: 63, code: "063", category: "Solitarios", name: "Único Sentimiento", description: "Una rosa solitaria que dice todo sin excesos. Perfecto para gestos simples pero cargados de significado profundo y sincero.", price: 18750, image: "assets/catalog/cod_063.webp" },
    { id: 64, code: "064", category: "Solitarios", name: "Dulce Gesto", description: "Una rosa acompañada de dulce selecto. Combina romance con sabor en detalle pequeño pero memorable para el corazón.", price: 75000, image: "assets/catalog/cod_064.webp" },
    { id: 66, code: "066", category: "Solitarios", name: "Sol y Dulzura", description: "Un girasol radiante con 2 dulces gourmet. Transmite alegría y sabor en gesto espontáneo que alegra cualquier día especial.", price: 87500, image: "assets/catalog/cod_066.webp" },
    { id: 67, code: "067", category: "Solitarios", name: "Dúo Luminoso", description: "Dos girasoles frescos acompañados de 2 dulces selectos. Perfecto para sorpresas simples que iluminan y endulzan la vida.", price: 100000, image: "assets/catalog/cod_067.webp" },
    { id: 68, code: "068", category: "Solitarios", name: "Doble Alegría", description: "Par de girasoles con 2 dulces en presentación delicada. Ideal para detalles espontáneos llenos de luz y buenos deseos.", price: 100000, image: "assets/catalog/cod_068.webp" },
    
    // Mezcla de Flores (69-77)
    { id: 69, code: "069", category: "Mezcla de Flores", name: "Jardín Primaveral", description: "Arreglo encantador con hortensias, rosas y margaritas frescas. Transmite frescura natural y amor en perfecta combinación de texturas.", price: 150000, image: "assets/catalog/cod_069.webp" },
    { id: 70, code: "070", category: "Mezcla de Flores", name: "Contraste Natural", description: "Bouquet vibrante de girasoles, cartuchos y follaje selecto. Diseñado para quienes aman la naturaleza en su máxima expresión auténtica.", price: 143750, image: "assets/catalog/cod_070.webp" },
    { id: 71, code: "071", category: "Mezcla de Flores", name: "Frescura Mixta", description: "Ramo delicado con hortensias, rosas y margaritas en armonía. Perfecto para sorprender con elegancia natural y colores suaves equilibrados.", price: 162500, image: "assets/catalog/cod_071.webp" },
    { id: 72, code: "072", category: "Mezcla de Flores", name: "Alegría Variada", description: "Arreglo alegre combinando margaritas y girasoles radiantes. Transmite felicidad pura y energía positiva en cada detalle floral cuidado.", price: 181250, image: "assets/catalog/cod_072.webp" },
    { id: 73, code: "073", category: "Mezcla de Flores", name: "Estrellas del Campo", description: "Bouquet romántico de claveles y estrellas de Belén. Representa amor sincero que brilla con luz propia en la oscuridad.", price: 175000, image: "assets/catalog/cod_073.webp" },
    { id: 75, code: "075", category: "Mezcla de Flores", name: "Fusión Suave", description: "Ramo elegante con rosas y astromelias delicadas. Combina romance con sutileza en presentación sofisticada y atemporal siempre bella.", price: 137500, image: "assets/catalog/cod_075.webp" },
    { id: 75.1, code: "075_a", category: "Mezcla de Flores", name: "Ternura Rosada", description: "Arreglo dulce de margaritas rosadas frescas. Transmite amor tierno, puro y lleno de inocencia natural que conquista corazones.", price: 137500, image: "assets/catalog/cod_075_a.webp" },
    { id: 76, code: "076", category: "Mezcla de Flores", name: "Campo de Luz", description: "Bouquet vibrante mezclando margaritas frescas y girasol radiante. Perfecto para celebrar la vida con alegría natural y espontánea.", price: 150000, image: "assets/catalog/cod_076.webp" },
    { id: 76.1, code: "076_a", category: "Mezcla de Flores", name: "Cielo Florido", description: "Ramo encantador de margaritas azules únicas. Representa amor sereno como el cielo, tranquilo pero infinito y profundo siempre.", price: 137500, image: "assets/catalog/cod_076_a.webp" },
    { id: 77, code: "077", category: "Mezcla de Flores", name: "Trío Vibrante", description: "Arreglo espectacular con rosas, gerberas y girasoles. Fusiona pasión, alegría y luz en presentación que roba miradas inmediatamente.", price: 187500, image: "assets/catalog/cod_077.webp" },
    
    // Lirios (78-80)
    { id: 78, code: "078", category: "Lirios", name: "Siete Elegantes", description: "Bouquet sofisticado con 7 lirios frescos aromáticos. Transmite pureza, amor y admiración en presentación elegante y atemporal.", price: 168750, image: "assets/catalog/cod_078.webp" },
    { id: 79, code: "079", category: "Lirios", name: "Pureza Abundante", description: "Ramo generoso de 10 lirios en presentación premium. Diseñado para expresar sentimientos puros con elegancia natural absoluta.", price: 212500, image: "assets/catalog/cod_079.webp" },
    { id: 80, code: "080", category: "Lirios", name: "Diez Majestuosos", description: "Arreglo imponente con 10 lirios seleccionados cuidadosamente. Perfecto para ocasiones especiales que merecen máxima distinción floral.", price: 225000, image: "assets/catalog/cod_080.webp" },
    
    // Bouquets en cascada (81-82)
    { id: 81, code: "081", category: "Bouquets en cascada", name: "Cascada Romántica", description: "Bouquet en cascada con 12 rosas frescas. Diseño único que fluye con gracia natural, perfecto para momentos especiales inolvidables.", price: 150000, image: "assets/catalog/cod_081.webp" },
    { id: 82, code: "082", category: "Bouquets en cascada", name: "Fluir del Amor", description: "Arreglo en cascada espectacular de 24 rosas. Representa amor que fluye sin obstáculos, libre y eternamente hermoso siempre.", price: 212500, image: "assets/catalog/cod_082.webp" },
    
    // Arreglos Florales en Base (84-100)
    { id: 84, code: "084", category: "Base", name: "Base Clásica", description: "Arreglo tradicional de rosas en base elegante. Perfecto para decorar espacios o regalar con estilo atemporal que nunca falla.", price: 175000, image: "assets/catalog/cod_084.webp" },
    { id: 85, code: "085", category: "Base", name: "Elegancia en Base", description: "Diseño sofisticado de rosas en base decorativa premium. Transmite amor con presentación que permanece y embellece cualquier espacio.", price: 225000, image: "assets/catalog/cod_085.webp" },
    { id: 86, code: "086", category: "Base", name: "Dulce Sofisticación", description: "Arreglo gourmet con rosas y chocolates JP Chanet selectos. Combina belleza visual con sabor exquisito en detalle irresistible completo.", price: 275000, image: "assets/catalog/cod_086.webp" },
    { id: 87, code: "087", category: "Base", name: "Oro en Base", description: "Diseño alegre de rosas amarillas en base elegante. Transmite amistad, gratitud y nuevos comienzos con luz radiante natural siempre.", price: 175000, image: "assets/catalog/cod_087.webp" },
    { id: 88, code: "088", category: "Base", name: "Guardián Dorado", description: "Arreglo especial de rosas amarillas con vela decorativa de oso. Combina alegría luminosa con ternura protectora en presentación única.", price: 212500, image: "assets/catalog/cod_088.webp" },
    { id: 89, code: "089", category: "Base", name: "Dulzura Dorada", description: "Diseño completo con rosas amarillas y chocolates selectos. Fusiona luz, alegría y sabor en regalo que conquista todos los sentidos.", price: 225000, image: "assets/catalog/cod_089.webp" },
    { id: 90, code: "090", category: "Base", name: "Esplendor Floral", description: "Arreglo abundante en base premium con flores selectas. Diseñado para impactar con belleza natural y elegancia sofisticada absoluta.", price: 362500, image: "assets/catalog/cod_090.webp" },
    { id: 91, code: "091", category: "Base", name: "Grandeza Natural", description: "Diseño majestuoso en base decorativa de alto impacto. Perfecto para ocasiones especiales que merecen máxima distinción floral memorable.", price: 425000, image: "assets/catalog/cod_091.webp" },
    { id: 92, code: "092", category: "Base", name: "Magnificencia Total", description: "Arreglo espectacular en base elegante con flores premium. Representa amor grande expresado con máxima belleza natural posible siempre.", price: 475000, image: "assets/catalog/cod_092.webp" },
    { id: 93, code: "093", category: "Base", name: "Jardín Premium", description: "Diseño sofisticado en base con variedad de flores selectas. Transmite amor abundante con presentación que embellece cualquier espacio especial.", price: 337500, image: "assets/catalog/cod_093.webp" },
    { id: 94, code: "094", category: "Base", name: "Abundancia Suprema", description: "Arreglo generoso en base decorativa de lujo. Diseñado para sorprender con cantidad, calidad y belleza natural desbordante siempre.", price: 412500, image: "assets/catalog/cod_094.webp" },
    { id: 95, code: "095", category: "Base", name: "Opulencia Floral", description: "Diseño lujoso en base premium con flores excepcionales. Perfecto para quienes buscan máxima elegancia y distinción natural absoluta.", price: 437500, image: "assets/catalog/cod_095.webp" },
    { id: 95.1, code: "095_a", category: "Base", name: "Lujo Absoluto", description: "Arreglo exclusivo en base de alta gama con flores únicas. Representa amor sin límites expresado con máximo refinamiento floral posible.", price: 487500, image: "assets/catalog/cod_095_a.webp" },
    { id: 96, code: "096", category: "Base", name: "Majestuosidad Pura", description: "Diseño imponente en base espectacular con flores premium selectas. Para ocasiones extraordinarias que merecen belleza sin igual memorable.", price: 612500, image: "assets/catalog/cod_096.webp" },
    { id: 97, code: "097", category: "Base", name: "Imperio Floral", description: "Arreglo monumental en base lujosa con variedad excepcional. Diseñado para impactar, conquistar y dejar huella imborrable en el alma.", price: 625000, image: "assets/catalog/cod_097.webp" },
    { id: 98, code: "098", category: "Base", name: "Elegancia Superior", description: "Diseño sofisticado en base decorativa con flores de calidad. Transmite amor con distinción natural que permanece en el tiempo siempre.", price: 312500, image: "assets/catalog/cod_098.webp" },
    { id: 99, code: "099", category: "Base", name: "Sofisticación Media", description: "Arreglo equilibrado en base elegante con flores frescas selectas. Perfecto para sorprender con estilo sin excesos pero con máximo impacto.", price: 275000, image: "assets/catalog/cod_099.webp" },
    { id: 100, code: "100", category: "Base", name: "Distinción Equilibrada", description: "Diseño armonioso en base decorativa con flores cuidadosamente seleccionadas. Representa amor expresado con balance perfecto siempre natural.", price: 275000, image: "assets/catalog/cod_100.webp" },
    
    // Arreglos Florales en Base de Corazones (101-108)
    { id: 101, code: "101", category: "Base de Corazones", name: "Corazón Delicado", description: "Arreglo romántico en base forma de corazón con flores frescas. Transmite amor sincero con presentación que habla directamente al alma.", price: 250000, image: "assets/catalog/cod_101.webp" },
    { id: 102, code: "102", category: "Base de Corazones", name: "Amor en Base", description: "Diseño encantador en corazón decorativo con flores selectas. Perfecto para expresar sentimientos profundos con símbolo universal del amor verdadero.", price: 275000, image: "assets/catalog/cod_102.webp" },
    { id: 103, code: "103", category: "Base de Corazones", name: "Corazón Clásico", description: "Arreglo tradicional en base corazón con flores elegantes. Representa amor atemporal que nunca pasa de moda ni pierde su esencia.", price: 250000, image: "assets/catalog/cod_103.webp" },
    { id: 104, code: "104", category: "Base de Corazones", name: "Corazón Grande", description: "Diseño abundante en base corazón con flores premium. Para quienes aman en grande y quieren expresarlo con símbolo perfecto siempre.", price: 375000, image: "assets/catalog/cod_104.webp" },
    { id: 105, code: "105", category: "Base de Corazones", name: "Corazón Supremo", description: "Arreglo espectacular en corazón lujoso con flores excepcionales. Transmite amor supremo con máxima belleza natural posible en presentación única.", price: 393750, image: "assets/catalog/cod_105.webp" },
    { id: 106, code: "106", category: "Base de Corazones", name: "Corazón Majestuoso", description: "Diseño imponente en base corazón con variedad floral premium. Perfecto para declaraciones importantes que merecen símbolo poderoso del amor.", price: 400000, image: "assets/catalog/cod_106.webp" },
    { id: 107, code: "107", category: "Base de Corazones", name: "Corazón Imperial", description: "Arreglo monumental en corazón elegante con flores selectas únicas. Representa amor que reina absoluto, fuerte y eternamente hermoso siempre.", price: 487500, image: "assets/catalog/cod_107.webp" },
    { id: 108, code: "108", category: "Base de Corazones", name: "Corazón Eterno", description: "Diseño inolvidable en base corazón con flores excepcionales premium. Para amores que trascienden el tiempo y merecen símbolo perfecto eternamente.", price: 500000, image: "assets/catalog/cod_108.webp" },
    
    // Arreglos florales en Base continuación (110-122)
    { id: 110, code: "110", category: "Base", name: "Base Encantadora", description: "Arreglo delicado en base decorativa con flores frescas seleccionadas. Transmite amor tierno con presentación que embellece espacios naturalmente siempre.", price: 193750, image: "assets/catalog/cod_110.webp" },
    { id: 111, code: "111", category: "Base", name: "Base Elegante", description: "Diseño sofisticado en base con flores de calidad premium. Perfecto para sorprender con distinción natural y belleza atemporal que permanece.", price: 212500, image: "assets/catalog/cod_111.webp" },
    { id: 112, code: "112", category: "Base", name: "Base Distinguida", description: "Arreglo refinado en base decorativa con flores cuidadosamente elegidas. Representa amor expresado con clase, estilo y elegancia natural absoluta.", price: 225000, image: "assets/catalog/cod_112.webp" },
    { id: 113, code: "113", category: "Base", name: "Base Armoniosa", description: "Diseño equilibrado en base con combinación perfecta de flores frescas. Transmite amor sereno en presentación que conquista con sutileza natural.", price: 225000, image: "assets/catalog/cod_113.webp" },
    { id: 114, code: "114", category: "Base", name: "Base Premium", description: "Arreglo de calidad superior en base elegante con flores selectas. Para quienes buscan belleza natural con distinción y sofisticación evidentes siempre.", price: 250000, image: "assets/catalog/cod_114.webp" },
    { id: 115, code: "115", category: "Base", name: "Base Sofisticada", description: "Diseño refinado en base decorativa con flores premium cuidadas. Perfecto para ocasiones especiales que merecen presentación impecable natural memorable.", price: 250000, image: "assets/catalog/cod_115.webp" },
    { id: 116, code: "116", category: "Base", name: "Base Superior", description: "Arreglo excepcional en base de lujo con variedad floral selecta. Transmite amor grande con máxima elegancia natural posible en cada detalle.", price: 275000, image: "assets/catalog/cod_116.webp" },
    { id: 117, code: "117", category: "Base", name: "Base Abundante", description: "Diseño generoso en base elegante con flores frescas abundantes. Representa amor desbordante expresado con belleza natural que impacta visualmente siempre.", price: 287500, image: "assets/catalog/cod_117.webp" },
    { id: 118, code: "118", category: "Base", name: "Base Espectacular", description: "Arreglo imponente en base decorativa con flores premium excepcionales. Para sorpresas grandes que necesitan presentación de máximo impacto visual.", price: 300000, image: "assets/catalog/cod_118.webp" },
    { id: 119, code: "119", category: "Base", name: "Base Magnífica", description: "Diseño majestuoso en base de lujo con variedad floral única. Perfecto para celebraciones importantes que merecen belleza natural sin igual memorable.", price: 300000, image: "assets/catalog/cod_119.webp" },
    { id: 120, code: "120", category: "Base", name: "Base Imponente", description: "Arreglo poderoso en base elegante con flores seleccionadas premium. Transmite amor fuerte con presentación que roba miradas desde primer instante.", price: 287500, image: "assets/catalog/cod_120.webp" },
    { id: 121, code: "121", category: "Base", name: "Base Majestuosa", description: "Diseño espectacular en base decorativa lujosa con flores excepcionales. Representa amor grande expresado con máxima distinción natural posible siempre.", price: 375000, image: "assets/catalog/cod_121.webp" },
    { id: 122, code: "122", category: "Base", name: "Base Imperial", description: "Arreglo monumental en base premium con variedad floral única selecta. Para ocasiones extraordinarias que merecen belleza suprema natural inolvidable eternamente.", price: 562500, image: "assets/catalog/cod_122.webp" },
    
    // ANCHETAS (123-133)
    { id: 123, code: "123", category: "ANCHETAS", name: "Ancheta Inicial", description: "Canasta regalo con combinación de flores y detalles especiales. Perfecto para sorprender con obsequio completo lleno de amor y buenos deseos.", price: 200000, image: "assets/catalog/cod_123.webp" },
    { id: 124, code: "124", category: "ANCHETAS", name: "Ancheta Encantadora", description: "Cesta decorativa con flores frescas y obsequios selectos. Ideal para celebrar momentos especiales con regalo que conquista todos los sentidos.", price: 237500, image: "assets/catalog/cod_124.webp" },
    { id: 125, code: "125", category: "ANCHETAS", name: "Ancheta Especial", description: "Canasta premium con flores y detalles cuidadosamente seleccionados. Transmite amor con obsequio completo que va más allá de las flores.", price: 237500, image: "assets/catalog/cod_125.webp" },
    { id: 126, code: "126", category: "ANCHETAS", name: "Ancheta Premium", description: "Cesta elegante con flores frescas y regalos de calidad superior. Perfecto para sorpresas grandes que merecen presentación impecable siempre memorable.", price: 275000, image: "assets/catalog/cod_126.webp" },
    { id: 127, code: "127", category: "ANCHETAS", name: "Ancheta Elegante", description: "Canasta sofisticada con flores premium y obsequios refinados selectos. Representa amor expresado con máxima distinción natural en regalo completo.", price: 275000, image: "assets/catalog/cod_127.webp" },
    { id: 128, code: "128", category: "ANCHETAS", name: "Ancheta Sofisticada", description: "Cesta de lujo con flores excepcionales y detalles exclusivos únicos. Para quienes buscan sorprender con obsequio de máximo refinamiento natural.", price: 287500, image: "assets/catalog/cod_128.webp" },
    { id: 129, code: "129", category: "ANCHETAS", name: "Ancheta Superior", description: "Canasta de alta gama con flores selectas y regalos premium. Transmite amor grande con presentación que supera todas las expectativas posibles.", price: 300000, image: "assets/catalog/cod_129.webp" },
    { id: 130, code: "130", category: "ANCHETAS", name: "Ancheta Distinguida", description: "Cesta elegante con flores frescas y obsequios de distinción evidente. Perfecta para ocasiones importantes que merecen regalo completo memorable siempre.", price: 300000, image: "assets/catalog/cod_130.webp" },
    { id: 131, code: "131", category: "ANCHETAS", name: "Ancheta Exclusiva", description: "Canasta única con flores excepcionales y detalles exclusivos selectos. Representa amor expresado con máxima personalización natural en obsequio especial.", price: 300000, image: "assets/catalog/cod_131.webp" },
    { id: 132, code: "132", category: "ANCHETAS", name: "Ancheta Majestuosa", description: "Cesta espectacular con flores premium y regalos de lujo absoluto. Para sorpresas extraordinarias que necesitan presentación de máximo impacto emocional.", price: 400000, image: "assets/catalog/cod_132.webp" },
    { id: 133, code: "133", category: "ANCHETAS", name: "Ancheta Imperial", description: "Canasta monumental con flores únicas y obsequios excepcionales premium. Transmite amor supremo con regalo completo de belleza natural sin igual eternamente.", price: 425000, image: "assets/catalog/cod_133.webp" }
];