// ===================================
// DATOS COMPLETOS DEL CATÁLOGO
// Familia de los Pétalos - Medellín
// ===================================

const products = [
    { id: 1, code: "001", category: "Anchetas con Peluche", name: "Abrazo de Osito", description: "Un oso grande y suave que se queda abrazado para siempre, acompañado de bombones finos, fruta fresca y globos que llenan el espacio de celebración. El regalo que ella vuelve a sentir cada vez que lo ve en su cuarto.", price: 437500, image: "assets/catalog/1.webp" },
    { id: 2, code: "002", category: "Anchetas con Peluche", name: "Ternura Gris", description: "Peluche de mirada dulce con moño, bombonera brillante y globo de confeti en tonos pastel. Perfecto para decirle lo que sientes sin tener que buscar las palabras.", price: 243750, image: "assets/catalog/2.webp" },
    { id: 3, code: "003", category: "Desayunos Sorpresa", name: "Brindis de Enamorados", description: "Bandeja en madera con flores frescas, fruta roja, vino y chocolates para compartir. Una mañana que deja de ser un día cualquiera y se convierte en la historia que van a contar por años.", price: 312500, image: "assets/catalog/3.webp" },
    { id: 4, code: "004", category: "Anchetas con Flores", name: "Explosión de Consentimiento", description: "Rosas rojas rodeadas de labiales, brillos, perfume y un peluche que la desarma por completo. El detalle más grande del catálogo, para la que merece sentirse la más importante del mundo.", price: 750000, image: "assets/catalog/4.webp" },
    { id: 5, code: "005", category: "Anchetas con Flores", name: "Cofre de Manzanas y Rosas", description: "Rosas rojas y fruta fresca en cofre de madera, con osito coronado y globos de corazón flotando arriba. Un regalo que se ve, se huele y se saborea al mismo tiempo.", price: 262500, image: "assets/catalog/5.webp" },
    { id: 6, code: "006", category: "Anchetas con Peluche", name: "Te Quiero Conmigo", description: "Rosas rojas envueltas en papel de gala con un osito que sostiene un corazón. Pequeño en tamaño y enorme en intención, ideal para ese \"pensé en ti\" que no necesita fecha especial.", price: 81250, image: "assets/catalog/6.webp" },
    { id: 7, code: "007", category: "Girasoles", name: "Buenos Días, Sol", description: "Girasoles abiertos con nube de gypsophila y un mensaje que ilumina el día completo. La forma más honesta de decir gracias, ánimo o simplemente \"te quieren\".", price: 87500, image: "assets/catalog/7.webp" },
    { id: 8, code: "008", category: "Girasoles con Chocolates", name: "Sol con Ferrero", description: "Girasoles en corona alrededor de un corazón de Ferrero Rocher, con eucalipto y toques azules. Alegría y dulzura en el mismo gesto, para quien te alegra a ti todos los días.", price: 225000, image: "assets/catalog/8.webp" },
    { id: 9, code: "009", category: "Rosas y Girasoles", name: "Fuego y Sol", description: "Rosas rojas apretadas alrededor de un girasol central sobre papel negro y dorado. La combinación que une pasión y alegría, imposible de ignorar en el momento de la entrega.", price: 175000, image: "assets/catalog/9.webp" },
    { id: 10, code: "010", category: "Rosas Rojas", name: "Reina del Día", description: "Rosas rojas y rosadas con corona y corazón de cristal en el centro, envueltas en rojo con filo dorado. Para la que siempre se pone de última y hoy le toca sentirse primera.", price: 225000, image: "assets/catalog/10.webp" },
    { id: 11, code: "011", category: "Rosas Rojas", name: "Clásico que Nunca Falla", description: "Rosas rojas con hypericum y follaje dorado en papel rojo rematado con moño de gala. La respuesta segura cuando quieres acertar sin pensarlo dos veces.", price: 112500, image: "assets/catalog/11.webp" },
    { id: 12, code: "012", category: "Combinación de Rosas", name: "Dulce Fucsia", description: "Rosas fucsia entre pompones blancos y rosados, envueltas en rojo con acabado dorado. Fresco, femenino y perfecto para llegar de sorpresa a la oficina o a la casa.", price: 81250, image: "assets/catalog/12.webp" },
    { id: 13, code: "013", category: "Cajas de Rosas", name: "Domo de Pasión", description: "Cúpula compacta de rosas rojas con gypsophila, base elegante y tarjeta con tu dedicatoria. Un detalle que se queda de adorno y sigue hablando por ti muchos días después.", price: 275000, image: "assets/catalog/13.webp" },
    { id: 14, code: "014", category: "Anchetas con Peluche", name: "Cofre de Ternura", description: "Osito crema con corazón de bombones dentro de una caja transparente lista para entregar. Delicado, limpio y directo al corazón, no necesita presentación.", price: 187500, image: "assets/catalog/14.webp" },
    { id: 15, code: "015", category: "Anchetas con Flores", name: "Mi Princesa", description: "Rosas rojas y fruta fresca en cofre de madera, con peluche coronado, globo Te Amo y tu mensaje escrito. El regalo con el que se quiebra cualquier resistencia.", price: 300000, image: "assets/catalog/15.webp" },
    { id: 16, code: "016", category: "Anchetas con Flores", name: "Rosé y Margaritas", description: "Margaritas fucsia, corazón de bombones y una copa de espumoso rosé junto a un osito suave. Para celebrar entre amigas, cerrar un logro o simplemente consentirla porque sí.", price: 237500, image: "assets/catalog/16.webp" },
    { id: 17, code: "017", category: "Rosas con Chocolates", name: "Noche de Ferrero", description: "Rosas rojas y margaritas sobre papel negro con dorado, coronadas por Ferrero Rocher y globo de corazón. Elegante, sabroso y con el punto justo de romanticismo.", price: 137500, image: "assets/catalog/17.webp" },
    { id: 18, code: "018", category: "Anchetas con Peluche", name: "Doble Compañía", description: "Dos ositos, rosas rojas y chocolates finos en cofre de madera con acabado azul. El regalo ideal para él, para papá o para celebrar una fecha en familia.", price: 275000, image: "assets/catalog/18.webp" },
    { id: 19, code: "019", category: "Rosas y Girasoles", name: "Sol y Pasión", description: "Girasoles y rosas rojas en presentación vertical con bombones y moño de raso. Un detalle esbelto, fácil de cargar y muy fotogénico en el momento de entregarlo.", price: 125000, image: "assets/catalog/19.webp" },
    { id: 20, code: "020", category: "Anchetas con Flores", name: "Eres Mi Favorita", description: "Oso suave, rosas rojas, bombones y globos que dicen exactamente lo que sientes. Una entrega que detiene la oficina y se vuelve la historia del día.", price: 350000, image: "assets/catalog/20.webp" },
    { id: 21, code: "021", category: "Girasoles", name: "Campo de Sol", description: "Girasoles generosos entre claveles rosados y gypsophila, envueltos en papel rosa suave. Un ramo imponente que transmite alegría antes de que alcance a leer la tarjeta.", price: 325000, image: "assets/catalog/21.webp" },
    { id: 22, code: "022", category: "Rosas y Girasoles", name: "Sombrerera Solar", description: "Girasoles y rosas rojas montados en sombrerera negra con moño de raso. Llega listo para poner en la mesa, sin florero y sin complicaciones.", price: 186000, image: "assets/catalog/22.webp" },
    { id: 23, code: "023", category: "Rosas Rojas", name: "Amor Sin Medida", description: "Un mar de rosas rojas bordeado de gypsophila sobre papel negro mate. Para propuestas, aniversarios grandes y momentos que no admiten término medio.", price: 621000, image: "assets/catalog/23.webp" },
    { id: 24, code: "024", category: "Rosas y Girasoles", name: "Sol de Media Tarde", description: "Girasoles con rosas rojas y gypsophila en papel negro con borde blanco. Alegre y romántico al mismo tiempo, acierta con mamá, con la pareja o con una amiga.", price: 101000, image: "assets/catalog/24.webp" },
    { id: 25, code: "025", category: "Cajas de Rosas con Chocolates", name: "Cofre Negro con Ferrero", description: "Rosas rojas sobre cama de gypsophila en caja negra con moño dorado y bombones Ferrero. Sobrio, elegante y con el detalle dulce que remata el gesto.", price: 153000, image: "assets/catalog/25.webp" },
    { id: 26, code: "026", category: "Combinación de Rosas", name: "Sencillo y Sincero", description: "Rosas rojas entre margaritas blancas en papel crema con moño de organza. La opción cómoda para decir gracias, perdón o \"me acordé de ti\".", price: 69000, image: "assets/catalog/26.webp" },
    { id: 27, code: "027", category: "Rosas Rojas", name: "Rojo Profundo", description: "Rosas rojas envueltas en nube de gypsophila y papel negro mate. El ramo clásico de aniversario, con la presentación que lo hace ver el doble de valioso.", price: 148000, image: "assets/catalog/27.webp" }
];
